import { useEffect, useState } from "react";
import { idOf } from "../../features/employees/employeeUtils";

function valuesFor(department) { return { name: department?.name ?? "", description: department?.description ?? "", manager: idOf(department?.manager) ?? "" }; }

export function DepartmentForm({ department, onSubmit, onCancel, isSubmitting }) {
  const [values, setValues] = useState(valuesFor(department));
  const [errors, setErrors] = useState({});
  useEffect(() => setValues(valuesFor(department)), [department]);
  function change(event) { setValues((current) => ({ ...current, [event.target.name]: event.target.value })); setErrors((current) => ({ ...current, [event.target.name]: "", form: "" })); }
  function validate() { const next = {}; if (values.name.trim().length < 2 || values.name.trim().length > 100) next.name = "Name must be between 2 and 100 characters."; if (values.description.length > 1000) next.description = "Description must be 1000 characters or fewer."; setErrors(next); return !Object.keys(next).length; }
  async function submit(event) { event.preventDefault(); if (!validate()) return; await onSubmit({ name: values.name.trim(), description: values.description.trim() || undefined, manager: values.manager.trim() || null }, setErrors); }
  return <form onSubmit={submit} className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm sm:p-8">{errors.form && <div className="mb-5 rounded-lg border border-rose-200 bg-rose-50 p-3 text-sm text-rose-800" role="alert">{errors.form}</div>}<div className="space-y-5"><label className="block text-sm font-semibold text-slate-700">Department name<input name="name" value={values.name} onChange={change} maxLength={100} required className={`mt-2 w-full rounded-lg border px-3 py-2.5 font-normal outline-none focus:border-indigo-500 ${errors.name ? "border-rose-400" : "border-slate-300"}`} />{errors.name && <span className="mt-1 block text-xs font-normal text-rose-700">{errors.name}</span>}</label><label className="block text-sm font-semibold text-slate-700">Description<span className="ml-2 text-xs font-normal text-slate-400">Optional</span><textarea name="description" value={values.description} onChange={change} maxLength={1000} rows={5} className={`mt-2 w-full resize-y rounded-lg border px-3 py-2.5 font-normal outline-none focus:border-indigo-500 ${errors.description ? "border-rose-400" : "border-slate-300"}`} />{errors.description && <span className="mt-1 block text-xs font-normal text-rose-700">{errors.description}</span>}</label><label className="block text-sm font-semibold text-slate-700">Manager employee ID<span className="ml-2 text-xs font-normal text-slate-400">Optional</span><input name="manager" value={values.manager} onChange={change} placeholder="Employee ObjectId" className="mt-2 w-full rounded-lg border border-slate-300 px-3 py-2.5 font-normal outline-none focus:border-indigo-500" /></label></div><div className="mt-7 flex justify-end gap-3"><button type="button" onClick={onCancel} className="rounded-lg border border-slate-300 px-4 py-2.5 text-sm font-semibold">Cancel</button><button disabled={isSubmitting} className="rounded-lg bg-indigo-600 px-5 py-2.5 text-sm font-semibold text-white hover:bg-indigo-700 disabled:opacity-50">{isSubmitting ? "Saving…" : department ? "Save changes" : "Create department"}</button></div></form>;
}

