import { useEffect, useState } from "react";
import { Link, useLocation, useNavigate, useParams } from "react-router-dom";
import { AttendanceForm } from "../components/attendance/AttendanceForm";
import { LoadingSkeleton } from "../components/ui/LoadingSkeleton";
import { createAttendance, listAttendance, updateAttendance } from "../services/attendanceApi";
import { listEmployees } from "../services/employeeApi";
import { ApiClientError } from "../services/apiClient";
import { useToast } from "../features/toasts/ToastContext";

export function AttendanceFormPage() { const { id } = useParams(); const location = useLocation(); const navigate = useNavigate(); const { showToast } = useToast(); const [record, setRecord] = useState(location.state?.record ?? null); const [employees, setEmployees] = useState([]); const [loading, setLoading] = useState(Boolean(id && !record)); const [error, setError] = useState(""); const [submitting, setSubmitting] = useState(false); useEffect(() => { Promise.all([listEmployees(), id && !record ? listAttendance() : Promise.resolve({ attendance: [] })]).then(([employeeResult, attendanceResult]) => { setEmployees(employeeResult.employees ?? []); if (!record && id) setRecord(attendanceResult.attendance?.find((item) => item._id === id) ?? null); }).catch((requestError) => setError(requestError instanceof ApiClientError ? requestError.message : "Unable to prepare the attendance form.")).finally(() => setLoading(false)); }, [id, record]); async function save(payload, setFieldErrors) { setSubmitting(true); try { const result = id ? await updateAttendance(id, payload) : await createAttendance(payload); showToast(id ? "Attendance record updated." : "Attendance marked successfully."); navigate(`/attendance/${result.attendance._id}`); } catch (requestError) { if (requestError.details?.length) { const mapped = {}; requestError.details.forEach((detail) => { mapped[detail.field || "form"] = detail.message; }); setFieldErrors(mapped); } else setError(requestError instanceof ApiClientError ? requestError.message : "Unable to save attendance."); } finally { setSubmitting(false); } } if (loading) return <LoadingSkeleton rows={6} />; return <div className="space-y-6"><Link to={id ? `/attendance/${id}` : "/attendance"} className="text-sm font-semibold text-indigo-600">← Cancel and go back</Link><div><p className="text-sm font-semibold text-indigo-600">WORKFORCE OPERATIONS</p><h1 className="mt-2 text-3xl font-bold tracking-tight">{id ? "Edit attendance" : "Mark attendance"}</h1><p className="mt-2 text-sm text-slate-600">Record monthly attendance using the backend-supported fields.</p></div>{error && <div className="rounded-xl border border-rose-200 bg-rose-50 p-4 text-sm text-rose-800" role="alert">{error}</div>}<AttendanceForm record={record} employees={employees} onSubmit={save} onCancel={() => navigate(id ? `/attendance/${id}` : "/attendance")} isSubmitting={submitting} /></div>; }

