import { useEffect, useMemo, useState } from "react";
import { useNavigate } from "react-router-dom";
import { DataTable } from "../components/ui/DataTable";
import { LoadingSkeleton } from "../components/ui/LoadingSkeleton";
import { Pagination } from "../components/ui/Pagination";
import { SearchBar } from "../components/ui/SearchBar";
import { listAttendance } from "../services/attendanceApi";
import { listEmployees } from "../services/employeeApi";
import { ApiClientError } from "../services/apiClient";
import { attendanceStatus, attendanceStatusLabels, formatPeriod } from "../features/attendance/attendanceUtils";
import { labelOf } from "../features/employees/employeeUtils";

export function AttendancePage() { const navigate = useNavigate(); const [records, setRecords] = useState([]); const [employees, setEmployees] = useState([]); const [query, setQuery] = useState(""); const [filters, setFilters] = useState({ employee: "", month: "", status: "" }); const [sort, setSort] = useState("period"); const [page, setPage] = useState(1); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const pageSize = 8;
  function load() { setLoading(true); const dateFilters = filters.month ? { from: `${filters.month}-01`, to: `${filters.month}-31` } : {}; Promise.all([listAttendance({ employee: filters.employee, ...dateFilters }), listEmployees().catch(() => ({ employees: [] }))]).then(([attendanceResult, employeeResult]) => { setRecords(attendanceResult.attendance ?? []); setEmployees(employeeResult.employees ?? []); setError(""); }).catch((requestError) => setError(requestError instanceof ApiClientError ? requestError.message : "Unable to load attendance records.")).finally(() => setLoading(false)); }
  useEffect(() => { load(); }, [filters.employee, filters.month]);
  const employeeMap = useMemo(() => new Map(employees.map((employee) => [employee._id, employee])), [employees]);
  const visible = useMemo(() => { const needle = query.toLowerCase().trim(); return records.filter((record) => { const employee = employeeMap.get(record.employee?._id ?? record.employee); const status = attendanceStatus(record); const text = `${employee?.employeeCode ?? ""} ${labelOf(employee?.user, "")} ${formatPeriod(record.period)}`.toLowerCase(); return (!needle || text.includes(needle)) && (!filters.status || status === filters.status); }).sort((a, b) => sort === "period" ? new Date(b.period) - new Date(a.period) : sort === "presentDays" ? b.presentDays - a.presentDays : b.absentDays - a.absentDays); }, [employeeMap, filters.status, query, records, sort]);
  const pageCount = Math.max(1, Math.ceil(visible.length / pageSize)); const rows = visible.slice((page - 1) * pageSize, page * pageSize); function filter(key, value) { setFilters((current) => ({ ...current, [key]: value })); setPage(1); }
  const columns = [{ key: "employee", header: "Employee", render: (row) => { const employee = employeeMap.get(row.employee?._id ?? row.employee); return <><span className="font-semibold text-slate-900">{employee?.employeeCode ?? "Employee"}</span><span className="block text-xs text-slate-500">{labelOf(employee?.user)}</span></>; } }, { key: "period", header: "Period", render: (row) => formatPeriod(row.period) }, { key: "status", header: "Status", render: (row) => <span className="rounded-full bg-indigo-50 px-2.5 py-1 text-xs font-semibold text-indigo-700">{attendanceStatusLabels[attendanceStatus(row)]}</span> }, { key: "presentDays", header: "Present", render: (row) => row.presentDays }, { key: "absentDays", header: "Absent", render: (row) => row.absentDays }];
  return <div className="space-y-6"><section className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="text-sm font-semibold text-indigo-600">WORKFORCE OPERATIONS</p><h1 className="mt-2 text-3xl font-bold tracking-tight">Attendance</h1><p className="mt-2 text-sm text-slate-600">Review monthly attendance records and maintain workforce presence data.</p></div><button onClick={() => navigate("/attendance/new")} className="rounded-lg bg-indigo-600 px-4 py-2.5 text-sm font-semibold text-white hover:bg-indigo-700">Mark attendance</button></section><div className="flex flex-col gap-3 rounded-2xl border border-slate-200 bg-white p-4 lg:flex-row"><SearchBar value={query} onChange={(value) => { setQuery(value); setPage(1); }} /><select aria-label="Employee filter" value={filters.employee} onChange={(event) => filter("employee", event.target.value)} className="rounded-lg border border-slate-300 bg-white px-3 py-2.5 text-sm"><option value="">All employees</option>{employees.map((employee) => <option key={employee._id} value={employee._id}>{employee.employeeCode}</option>)}</select><label className="flex items-center gap-2 rounded-lg border border-slate-300 bg-white px-3 py-2 text-sm text-slate-600">Month<input aria-label="Month filter" type="month" value={filters.month} onChange={(event) => filter("month", event.target.value)} className="font-medium text-slate-800 outline-none" /></label><select aria-label="Attendance status filter" value={filters.status} onChange={(event) => filter("status", event.target.value)} className="rounded-lg border border-slate-300 bg-white px-3 py-2.5 text-sm"><option value="">All statuses</option><option value="present">Present</option><option value="absent">Absent</option><option value="mixed">Mixed</option></select><select aria-label="Sort attendance" value={sort} onChange={(event) => setSort(event.target.value)} className="rounded-lg border border-slate-300 bg-white px-3 py-2.5 text-sm"><option value="period">Most recent</option><option value="presentDays">Most present</option><option value="absentDays">Most absent</option></select></div>{loading ? <LoadingSkeleton /> : error ? <div className="rounded-2xl border border-rose-200 bg-rose-50 p-6 text-sm text-rose-800" role="alert">{error}<button onClick={load} className="ml-3 font-semibold underline">Retry</button></div> : <><DataTable columns={columns} rows={rows} onRowClick={(row) => navigate(`/attendance/${row._id}`, { state: { record: row, employee: employeeMap.get(row.employee?._id ?? row.employee) } })} emptyMessage="No attendance records match your search and filters." /><Pagination page={page} pageCount={pageCount} total={visible.length} onChange={setPage} /></>}</div>; }

