import { useEffect, useState } from "react";
import { Link, useLocation, useNavigate, useParams } from "react-router-dom";
import { LoadingSkeleton } from "../components/ui/LoadingSkeleton";
import { listAttendance } from "../services/attendanceApi";
import { getEmployee } from "../services/employeeApi";
import { ApiClientError } from "../services/apiClient";
import { attendanceStatus, attendanceStatusLabels, formatPeriod } from "../features/attendance/attendanceUtils";
import { labelOf } from "../features/employees/employeeUtils";

export function AttendanceDetailsPage() { const { id } = useParams(); const location = useLocation(); const navigate = useNavigate(); const [record, setRecord] = useState(location.state?.record ?? null); const [employee, setEmployee] = useState(location.state?.employee ?? null); const [error, setError] = useState(""); useEffect(() => { listAttendance().then((result) => { const found = record ?? result.attendance?.find((item) => item._id === id); if (!found) throw new ApiClientError("Attendance record not found."); setRecord(found); const employeeId = found.employee?._id ?? found.employee; if (!employee && employeeId) return getEmployee(employeeId).then((employeeResult) => setEmployee(employeeResult.employee)).catch(() => undefined); return undefined; }).catch((requestError) => setError(requestError instanceof ApiClientError ? requestError.message : "Unable to load this attendance record.")); }, [id]); return <div className="space-y-6"><div className="flex items-center justify-between gap-3"><Link to="/attendance" className="text-sm font-semibold text-indigo-600">← Back to attendance</Link>{record && <button onClick={() => navigate(`/attendance/${id}/edit`, { state: { record, employee } })} className="rounded-lg border border-slate-300 px-4 py-2 text-sm font-semibold">Edit record</button>}</div>{error ? <div className="rounded-2xl border border-rose-200 bg-rose-50 p-6 text-sm text-rose-800" role="alert">{error}</div> : record ? <><div><p className="text-sm font-semibold text-indigo-600">ATTENDANCE RECORD</p><h1 className="mt-2 text-3xl font-bold tracking-tight">{formatPeriod(record.period)}</h1></div><section className="grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{[["Employee", labelOf(employee?.user, employee?.employeeCode || record.employee)], ["Status", attendanceStatusLabels[attendanceStatus(record)]], ["Period", formatPeriod(record.period)], ["Working days", record.workingDays], ["Present days", record.presentDays], ["Absent days", record.absentDays], ["Overtime hours", record.overtimeHours]].map(([label, value]) => <article key={label} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><p className="text-xs font-semibold uppercase tracking-wide text-slate-400">{label}</p><p className="mt-2 text-lg font-semibold text-slate-900">{value}</p></article>)}</section><p className="text-sm text-slate-500">Notes are not part of the current attendance contract.</p></> : <LoadingSkeleton rows={6} />}</div>; }
