import { useRef, useState } from "react";
import { askCopilot } from "../services/copilotApi";
import { ApiClientError } from "../services/apiClient";

const starters = ["How do I request planned leave?", "What does the handbook say about confidentiality?"];

export function CopilotPage() {
  const [messages, setMessages] = useState([]); const [question, setQuestion] = useState(""); const [isSending, setIsSending] = useState(false); const [error, setError] = useState(""); const inputRef = useRef(null);
  async function send(nextQuestion = question) {
    const text = nextQuestion.trim(); if (!text || isSending) return;
    const history = messages.slice(-8).map(({ role, content }) => ({ role, content })); const userMessage = { id: crypto.randomUUID(), role: "user", content: text };
    setMessages((current) => [...current, userMessage]); setQuestion(""); setError(""); setIsSending(true);
    try {
      const result = await askCopilot({ question: text, history });
      setMessages((current) => [...current, { id: crypto.randomUUID(), role: "assistant", content: result.answer, sources: result.sources ?? [], confidence: result.confidence }]);
    } catch (requestError) { setError(requestError instanceof ApiClientError ? requestError.message : "Unable to reach HR Copilot."); }
    finally { setIsSending(false); inputRef.current?.focus(); }
  }
  return <div className="mx-auto flex max-w-5xl flex-col gap-6"><section className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="text-sm font-semibold text-indigo-600">HR KNOWLEDGE</p><h1 className="mt-2 text-3xl font-bold tracking-tight sm:text-4xl">HR Copilot</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-slate-600">Ask about approved HR policies. Every answer is grounded in retrieved policy evidence.</p></div><button onClick={() => { setMessages([]); setError(""); inputRef.current?.focus(); }} className="rounded-lg border border-slate-300 bg-white px-4 py-2.5 text-sm font-semibold text-slate-700 hover:bg-slate-50">New conversation</button></section><section className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="border-b border-indigo-100 bg-indigo-50 px-5 py-4 text-sm text-indigo-900"><span className="font-semibold">Evidence-only answers.</span> If the approved knowledge base does not contain the policy, Copilot will say so instead of guessing.</div><div className="min-h-[420px] space-y-5 p-4 sm:p-6" aria-live="polite">{messages.length ? messages.map((message) => <ChatMessage key={message.id} message={message} />) : <EmptyState onStarter={send} />}{isSending && <TypingIndicator />}{error && <div className="rounded-xl border border-rose-200 bg-rose-50 p-4 text-sm text-rose-800" role="alert">{error}<button onClick={() => setError("")} className="ml-3 font-semibold underline">Dismiss</button></div>}</div><form onSubmit={(event) => { event.preventDefault(); send(); }} className="border-t border-slate-200 bg-slate-50 p-4"><label htmlFor="copilot-question" className="sr-only">Ask an HR policy question</label><div className="flex flex-col gap-3 sm:flex-row sm:items-end"><textarea ref={inputRef} id="copilot-question" value={question} onChange={(event) => setQuestion(event.target.value)} onKeyDown={(event) => { if (event.key === "Enter" && (event.ctrlKey || event.metaKey)) { event.preventDefault(); send(); } }} rows={3} maxLength={1000} placeholder="Ask about leave, benefits, remote work, or workplace policies…" className="min-h-24 flex-1 resize-none rounded-xl border border-slate-300 bg-white px-3 py-2.5 text-sm leading-6 outline-none transition focus:border-indigo-500 focus:ring-3 focus:ring-indigo-100" disabled={isSending} /><button disabled={!question.trim() || isSending} className="rounded-xl bg-indigo-600 px-5 py-3 text-sm font-semibold text-white hover:bg-indigo-700 disabled:cursor-not-allowed disabled:opacity-50">{isSending ? "Thinking…" : "Send"}</button></div><p className="mt-2 text-xs text-slate-500">Ctrl/⌘ + Enter to send. Do not include personal or confidential employee information.</p></form></section></div>;
}

function EmptyState({ onStarter }) { return <div className="grid min-h-[360px] place-items-center text-center"><div className="max-w-lg"><div className="mx-auto grid size-12 place-items-center rounded-2xl bg-indigo-100 text-xl text-indigo-700">✦</div><h2 className="mt-4 text-xl font-bold text-slate-900">How can I help with an HR policy?</h2><p className="mt-2 text-sm leading-6 text-slate-600">I’ll search the approved knowledge base and show the supporting policy excerpts with every answer.</p><div className="mt-5 flex flex-wrap justify-center gap-2">{starters.map((starter) => <button key={starter} onClick={() => onStarter(starter)} className="rounded-full border border-indigo-200 bg-white px-3 py-2 text-xs font-semibold text-indigo-700 hover:bg-indigo-50">{starter}</button>)}</div></div></div>; }
function TypingIndicator() { return <div className="flex gap-3"><Avatar role="assistant" /><div className="rounded-2xl rounded-tl-sm bg-slate-100 px-4 py-3"><span className="flex gap-1" aria-label="Copilot is thinking"><i className="size-2 animate-bounce rounded-full bg-slate-400 [animation-delay:-0.2s]" /><i className="size-2 animate-bounce rounded-full bg-slate-400 [animation-delay:-0.1s]" /><i className="size-2 animate-bounce rounded-full bg-slate-400" /></span></div></div>; }
function ChatMessage({ message }) { const assistant = message.role === "assistant"; return <article className={`flex gap-3 ${assistant ? "" : "flex-row-reverse"}`}><Avatar role={message.role} /><div className={`max-w-3xl ${assistant ? "" : "text-right"}`}><p className="mb-1 text-xs font-semibold uppercase tracking-wide text-slate-400">{assistant ? "HR Copilot" : "You"}</p><div className={`rounded-2xl px-4 py-3 text-sm leading-6 ${assistant ? "rounded-tl-sm bg-slate-100 text-slate-800" : "rounded-tr-sm bg-indigo-600 text-white"}`}><p className="whitespace-pre-wrap">{message.content}</p></div>{assistant && <><Confidence confidence={message.confidence} /><Sources sources={message.sources} /></>}</div></article>; }
function Avatar({ role }) { return <div className={`grid size-9 shrink-0 place-items-center rounded-xl text-sm font-bold ${role === "assistant" ? "bg-indigo-100 text-indigo-700" : "bg-slate-800 text-white"}`}>{role === "assistant" ? "P" : "Y"}</div>; }
function Confidence({ confidence }) { if (!confidence) return null; const tone = confidence.level === "high" ? "text-emerald-700" : confidence.level === "medium" ? "text-amber-700" : "text-slate-600"; return <p className={`mt-2 text-xs ${tone}`}>{confidence.grounded ? `${confidence.level[0].toUpperCase()}${confidence.level.slice(1)} evidence confidence · ${confidence.evidenceCount} source${confidence.evidenceCount === 1 ? "" : "s"}` : "No sufficiently relevant approved policy evidence was found."}</p>; }
function Sources({ sources = [] }) { return sources.length ? <section className="mt-3 space-y-2"><p className="text-xs font-semibold uppercase tracking-wide text-slate-400">Supporting sources</p>{sources.map((source) => <details key={source.id} className="rounded-xl border border-slate-200 bg-white p-3"><summary className="cursor-pointer list-none text-sm font-semibold text-slate-800"><span className="mr-2 rounded bg-indigo-50 px-1.5 py-0.5 text-xs text-indigo-700">[{source.id}]</span>{source.document}<span className="ml-2 text-xs font-medium text-slate-500">{source.section} · {(source.score * 100).toFixed(0)}%</span></summary><p className="mt-3 whitespace-pre-wrap border-t border-slate-100 pt-3 text-sm leading-6 text-slate-600">{source.excerpt}</p>{source.page && <p className="mt-2 text-xs text-slate-400">Page {source.page}</p>}</details>)}</section> : null; }
