import { useEffect, useState } from "react";
import { Link } from "react-router-dom";
import { useAuth } from "../features/auth/AuthContext";
import { listAttendance } from "../services/attendanceApi";
import { listLatestAttritionPredictions } from "../services/attritionPredictionApi";
import { listDepartments } from "../services/departmentApi";
import { listEmployees } from "../services/employeeApi";
import { listFeedback } from "../services/feedbackApi";
import { listPerformanceReviews } from "../services/performanceReviewApi";
import { listSurveys } from "../services/surveyApi";
import { averageSurveyScore, formatDate } from "../features/engagement/engagementUtils";

const copy = { employee: ["Your workspace", "View the records and employee experience actions available to you."], manager: ["Team workspace", "Monitor authorized workforce, performance, engagement, and risk signals."], hr: ["HR operations workspace", "A live executive view of people operations and engagement."], admin: ["Administration workspace", "Organization-wide workforce operations, experience, and risk indicators."] };
const tones = { indigo: "border-indigo-100 bg-indigo-50 text-indigo-700", violet: "border-violet-100 bg-violet-50 text-violet-700", emerald: "border-emerald-100 bg-emerald-50 text-emerald-700", amber: "border-amber-100 bg-amber-50 text-amber-700", sky: "border-sky-100 bg-sky-50 text-sky-700", rose: "border-rose-100 bg-rose-50 text-rose-700" };
function Card({ label, value, detail, tone = "indigo" }) { return <article className={`rounded-2xl border p-5 ${tones[tone]}`}><p className="text-xs font-semibold uppercase tracking-wide">{label}</p><p className="mt-2 text-3xl font-bold text-slate-950">{value}</p><p className="mt-1 text-sm text-slate-600">{detail}</p></article>; }
function Panel({ title, href, children }) { return <section className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><div className="flex items-center justify-between gap-4"><h2 className="text-lg font-bold">{title}</h2>{href && <Link to={href} className="text-sm font-semibold text-indigo-600">View all</Link>}</div><div className="mt-5">{children}</div></section>; }

export function DashboardPage() {
  const { user } = useAuth(); const canAnalyze = ["manager", "hr", "admin"].includes(user.role); const [result, setResult] = useState(null); const [loading, setLoading] = useState(canAnalyze); const [title, description] = copy[user.role] ?? copy.employee;
  useEffect(() => { if (!canAnalyze) return undefined; let current = true; Promise.all([listEmployees().catch(() => null), listDepartments().catch(() => null), listAttendance().catch(() => null), listPerformanceReviews().catch(() => null), listSurveys().catch(() => null), listFeedback().catch(() => null), listLatestAttritionPredictions().catch(() => null)]).then(([employees, departments, attendance, reviews, surveys, feedback, predictions]) => { if (current) { setResult({ employees, departments, attendance, reviews, surveys, feedback, predictions }); setLoading(false); } }); return () => { current = false; }; }, [canAnalyze]);
  if (!canAnalyze) return <div className="space-y-8"><Header role={user.role} title={title} description={description} /><Panel title="Employee experience"><p className="text-sm leading-6 text-slate-600">Share your perspective through the engagement suite.</p><div className="mt-5 flex gap-3"><Link to="/surveys/new" className="rounded-lg bg-indigo-600 px-4 py-2.5 text-sm font-semibold text-white">Take survey</Link><Link to="/feedback/new" className="rounded-lg border border-slate-300 px-4 py-2.5 text-sm font-semibold">Share feedback</Link></div></Panel></div>;
  const attendance = result?.attendance?.attendance ?? []; const reviews = result?.reviews?.reviews ?? []; const surveys = result?.surveys?.surveys ?? []; const feedback = result?.feedback?.feedback ?? []; const predictions = result?.predictions?.predictions ?? []; const reviewAverage = reviews.length ? (reviews.reduce((sum, item) => sum + item.rating, 0) / reviews.length).toFixed(1) : "0.0"; const surveyAverage = surveys.length ? (surveys.reduce((sum, item) => sum + averageSurveyScore(item), 0) / surveys.length).toFixed(1) : "0.0"; const activity = [...reviews.slice(0, 2).map((item) => ({ label: `Review · ${item.rating}/5`, date: item.createdAt })), ...surveys.slice(0, 2).map((item) => ({ label: `Survey · ${averageSurveyScore(item).toFixed(1)}/5`, date: item.submittedAt })), ...feedback.slice(0, 2).map((item) => ({ label: "Feedback received", date: item.submittedAt }))].sort((a, b) => new Date(b.date) - new Date(a.date)).slice(0, 5);
  return <div className="space-y-8"><Header role={user.role} title={title} description={description} />{loading ? <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{Array.from({ length: 8 }, (_, index) => <div key={index} className="h-32 animate-pulse rounded-2xl bg-slate-100" />)}</div> : <><section className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-6"><Card label="Employees" value={result?.employees?.employees?.length ?? "—"} detail="Authorized workforce" /><Card label="Departments" value={result?.departments?.departments?.length ?? "—"} detail="Organization units" tone="violet" /><Card label="Attendance" value={attendance.length} detail={`${attendance.reduce((sum, item) => sum + item.presentDays, 0)} present days`} tone="emerald" /><Card label="Reviews" value={reviews.length} detail={`${reviewAverage}/5 average rating`} tone="amber" /><Card label="Surveys" value={surveys.length} detail={`${surveyAverage}/5 average score`} tone="sky" /><Card label="Feedback" value={feedback.length} detail={`${feedback.filter((item) => item.sentimentLabel === "positive").length} positive signals`} tone="rose" /></section><section className="grid gap-4 sm:grid-cols-3"><Card label="High risk" value={predictions.filter((item) => item.riskLevel === "high").length} detail="Latest predictions" tone="rose" /><Card label="Medium risk" value={predictions.filter((item) => item.riskLevel === "medium").length} detail="Latest predictions" tone="amber" /><Card label="Low risk" value={predictions.filter((item) => item.riskLevel === "low").length} detail="Latest predictions" tone="emerald" /></section><section className="grid gap-5 lg:grid-cols-2"><Panel title="Latest predictions"><div className="space-y-3">{predictions.length ? predictions.slice(0, 5).map((item) => <div key={item._id} className="flex items-center justify-between rounded-lg border border-slate-100 p-3"><div><p className="text-sm font-semibold">{item.employee?.employeeCode ?? "Employee"}</p><p className="text-xs text-slate-500">{formatDate(item.predictedAt)} · {item.modelVersion}</p></div><span className={`rounded-full px-2.5 py-1 text-xs font-semibold ${item.riskLevel === "high" ? "bg-rose-50 text-rose-700" : item.riskLevel === "medium" ? "bg-amber-50 text-amber-700" : "bg-emerald-50 text-emerald-700"}`}>{(item.probability * 100).toFixed(1)}% · {item.riskLevel}</span></div>) : <p className="text-sm text-slate-500">No predictions have been generated yet.</p>}</div></Panel><Panel title="Recent activity"><div className="space-y-3">{activity.length ? activity.map((item, index) => <div key={`${item.label}-${index}`} className="flex justify-between rounded-lg border border-slate-100 p-3 text-sm"><span className="font-medium">{item.label}</span><span className="text-slate-500">{formatDate(item.date)}</span></div>) : <p className="text-sm text-slate-500">No recent activity.</p>}</div></Panel></section></>}</div>;
}
function Header({ role, title, description }) { return <section><p className="text-sm font-semibold text-indigo-600">{role.toUpperCase()} DASHBOARD</p><h1 className="mt-2 text-3xl font-bold tracking-tight sm:text-4xl">{title}</h1><p className="mt-3 max-w-3xl text-base leading-7 text-slate-600">{description}</p></section>; }
