import { useEffect, useState } from "react";
import { Link, useNavigate, useParams } from "react-router-dom";
import { DepartmentForm } from "../components/departments/DepartmentForm";
import { LoadingSkeleton } from "../components/ui/LoadingSkeleton";
import { createDepartment, getDepartment, updateDepartment } from "../services/departmentApi";
import { ApiClientError } from "../services/apiClient";
import { useToast } from "../features/toasts/ToastContext";

export function DepartmentFormPage() { const { id } = useParams(); const navigate = useNavigate(); const { showToast } = useToast(); const [department, setDepartment] = useState(null); const [loading, setLoading] = useState(Boolean(id)); const [error, setError] = useState(""); const [submitting, setSubmitting] = useState(false); useEffect(() => { if (!id) return undefined; getDepartment(id).then((result) => setDepartment(result.department)).catch((requestError) => setError(requestError instanceof ApiClientError ? requestError.message : "Unable to prepare the department form.")).finally(() => setLoading(false)); return undefined; }, [id]); async function save(payload, setFieldErrors) { setSubmitting(true); try { const result = id ? await updateDepartment(id, payload) : await createDepartment(payload); showToast(id ? "Department updated successfully." : "Department created successfully."); navigate(`/departments/${result.department._id}`); } catch (requestError) { if (requestError.details?.length) { const mapped = {}; requestError.details.forEach((detail) => { mapped[detail.field || "form"] = detail.message; }); setFieldErrors(mapped); } else { setError(requestError instanceof ApiClientError ? requestError.message : "Unable to save department."); } } finally { setSubmitting(false); } } if (loading) return <LoadingSkeleton rows={5} />; return <div className="space-y-6"><Link to={id ? `/departments/${id}` : "/departments"} className="text-sm font-semibold text-indigo-600">← Cancel and go back</Link><div><p className="text-sm font-semibold text-indigo-600">ORGANIZATION STRUCTURE</p><h1 className="mt-2 text-3xl font-bold tracking-tight">{id ? "Edit department" : "Create department"}</h1><p className="mt-2 text-sm text-slate-600">Use the fields supported by the department API.</p></div>{error && <div className="rounded-xl border border-rose-200 bg-rose-50 p-4 text-sm text-rose-800" role="alert">{error}</div>}<DepartmentForm department={department} onSubmit={save} onCancel={() => navigate(id ? `/departments/${id}` : "/departments")} isSubmitting={submitting} /></div>; }

