import { useEffect, useState } from "react";
import { Link, useNavigate, useParams } from "react-router-dom";
import { LoadingSkeleton } from "../components/ui/LoadingSkeleton";
import { getDepartment } from "../services/departmentApi";
import { ApiClientError } from "../services/apiClient";
import { labelOf } from "../features/employees/employeeUtils";

export function DepartmentDetailsPage() { const { id } = useParams(); const navigate = useNavigate(); const [department, setDepartment] = useState(null); const [error, setError] = useState(""); useEffect(() => { getDepartment(id).then((result) => setDepartment(result.department)).catch((requestError) => setError(requestError instanceof ApiClientError ? requestError.message : "Unable to load this department.")); }, [id]); return <div className="space-y-6"><div className="flex items-center justify-between gap-3"><Link to="/departments" className="text-sm font-semibold text-indigo-600">← Back to departments</Link>{department && <button onClick={() => navigate(`/departments/${id}/edit`)} className="rounded-lg border border-slate-300 px-4 py-2 text-sm font-semibold">Edit department</button>}</div>{error ? <div className="rounded-2xl border border-rose-200 bg-rose-50 p-6 text-sm text-rose-800" role="alert">{error}</div> : department ? <><div><p className="text-sm font-semibold text-indigo-600">DEPARTMENT PROFILE</p><h1 className="mt-2 text-3xl font-bold tracking-tight">{department.name}</h1></div><section className="grid gap-5 md:grid-cols-2"><article className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><p className="text-xs font-semibold uppercase tracking-wide text-slate-400">Description</p><p className="mt-3 text-sm leading-7 text-slate-700">{department.description || "No description provided."}</p></article><article className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><p className="text-xs font-semibold uppercase tracking-wide text-slate-400">Manager</p><p className="mt-3 text-sm font-medium text-slate-800">{labelOf(department.manager)}</p><p className="mt-6 text-xs text-slate-500">Employee count and related employees are not included in the current department API response.</p></article></section></> : <LoadingSkeleton rows={5} />}</div>; }

