import { useEffect, useMemo, useState } from "react";
import { useNavigate } from "react-router-dom";
import { DataTable } from "../components/ui/DataTable";
import { FilterBar } from "../components/ui/FilterBar";
import { LoadingSkeleton } from "../components/ui/LoadingSkeleton";
import { Pagination } from "../components/ui/Pagination";
import { SearchBar } from "../components/ui/SearchBar";
import { listDepartments } from "../services/departmentApi";
import { listEmployees } from "../services/employeeApi";
import { formatDate, idOf, labelOf, statusLabels } from "../features/employees/employeeUtils";
import { ApiClientError } from "../services/apiClient";

export function EmployeesPage() { const navigate = useNavigate(); const [employees, setEmployees] = useState([]); const [departments, setDepartments] = useState([]); const [query, setQuery] = useState(""); const [filters, setFilters] = useState({ department: "", role: "", employmentStatus: "" }); const [sort, setSort] = useState("createdAt"); const [page, setPage] = useState(1); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const pageSize = 8;
  useEffect(() => { Promise.all([listEmployees({ department: filters.department, employmentStatus: filters.employmentStatus }), listDepartments().catch(() => ({ departments: [] }))]).then(([employeeResult, departmentResult]) => { setEmployees(employeeResult.employees ?? []); setDepartments(departmentResult.departments ?? []); setError(""); }).catch((requestError) => setError(requestError instanceof ApiClientError ? requestError.message : "Unable to load employees.")).finally(() => setLoading(false)); }, [filters.department, filters.employmentStatus]);
  const visible = useMemo(() => { const needle = query.toLowerCase().trim(); return employees.filter((employee) => { const haystack = [employee.employeeCode, employee.designation, labelOf(employee.user, ""), labelOf(employee.department, "")].join(" ").toLowerCase(); const role = employee.user?.role; return (!needle || haystack.includes(needle)) && (!filters.role || role === filters.role); }).sort((a, b) => { const av = sort === "department" ? labelOf(a.department) : sort === "status" ? a.employmentStatus : a[sort]; return String(av ?? "").localeCompare(String(sort === "department" ? labelOf(b.department) : sort === "status" ? b.employmentStatus : b[sort] ?? "")); }); }, [employees, filters.role, query, sort]);
  const pageCount = Math.max(1, Math.ceil(visible.length / pageSize)); const rows = visible.slice((page - 1) * pageSize, page * pageSize);
  function changeFilter(key, value) { setFilters((current) => ({ ...current, [key]: value })); setPage(1); }
  const columns = [{ key: "employeeCode", header: "Employee", render: (row) => <><span className="font-semibold text-slate-900">{row.employeeCode}</span><span className="block text-xs text-slate-500">{labelOf(row.user)}</span></> }, { key: "designation", header: "Designation" }, { key: "department", header: "Department", render: (row) => labelOf(row.department) }, { key: "employmentStatus", header: "Status", render: (row) => <span className="rounded-full bg-emerald-50 px-2.5 py-1 text-xs font-semibold text-emerald-700">{statusLabels[row.employmentStatus] ?? row.employmentStatus}</span> }, { key: "dateOfJoining", header: "Joined", render: (row) => formatDate(row.dateOfJoining) }];
  return <div className="space-y-6"><section className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="text-sm font-semibold text-indigo-600">PEOPLE OPERATIONS</p><h1 className="mt-2 text-3xl font-bold tracking-tight">Employees</h1><p className="mt-2 text-sm text-slate-600">Search and manage the workforce records available to your role.</p></div><button onClick={() => navigate("/employees/new")} className="rounded-lg bg-indigo-600 px-4 py-2.5 text-sm font-semibold text-white hover:bg-indigo-700">Add employee</button></section><div className="flex flex-col gap-3 rounded-2xl border border-slate-200 bg-white p-4 shadow-sm lg:flex-row"><SearchBar value={query} onChange={(value) => { setQuery(value); setPage(1); }} /><FilterBar filters={filters} onChange={changeFilter} departments={departments} /><select aria-label="Sort employees" value={sort} onChange={(event) => setSort(event.target.value)} className="rounded-lg border border-slate-300 bg-white px-3 py-2.5 text-sm"><option value="createdAt">Newest first</option><option value="employeeCode">Employee code</option><option value="department">Department</option><option value="status">Status</option></select></div>{loading ? <LoadingSkeleton /> : error ? <div className="rounded-2xl border border-rose-200 bg-rose-50 p-6 text-sm text-rose-800" role="alert">{error}<button onClick={() => window.location.reload()} className="ml-3 font-semibold underline">Retry</button></div> : <><DataTable columns={columns} rows={rows} onRowClick={(row) => navigate(`/employees/${idOf(row)}`)} emptyMessage="No employees match your current search and filters." /><Pagination page={page} pageCount={pageCount} total={visible.length} onChange={setPage} /></>}</div>; }

