import { useEffect, useState } from "react";
import { Link, useNavigate, useParams } from "react-router-dom";
import { EmployeeForm } from "../components/employees/EmployeeForm";
import { LoadingSkeleton } from "../components/ui/LoadingSkeleton";
import { getEmployee, createEmployee, updateEmployee } from "../services/employeeApi";
import { listDepartments } from "../services/departmentApi";
import { ApiClientError } from "../services/apiClient";
import { useToast } from "../features/toasts/ToastContext";

export function EmployeeFormPage() { const { id } = useParams(); const navigate = useNavigate(); const { showToast } = useToast(); const [employee, setEmployee] = useState(null); const [departments, setDepartments] = useState([]); const [loading, setLoading] = useState(Boolean(id)); const [error, setError] = useState(""); const [submitting, setSubmitting] = useState(false); useEffect(() => { Promise.all([listDepartments(), id ? getEmployee(id) : Promise.resolve({ employee: null })]).then(([departmentResult, employeeResult]) => { setDepartments(departmentResult.departments ?? []); setEmployee(employeeResult.employee); }).catch((requestError) => setError(requestError instanceof ApiClientError ? requestError.message : "Unable to prepare the employee form.")).finally(() => setLoading(false)); }, [id]); async function save(payload, setFieldErrors) { setSubmitting(true); try { const result = id ? await updateEmployee(id, payload) : await createEmployee(payload); showToast(id ? "Employee profile updated." : "Employee created successfully."); navigate(`/employees/${result.employee._id}`); } catch (requestError) { if (requestError.details?.length) { const mapped = {}; requestError.details.forEach((detail) => { mapped[detail.field || "form"] = detail.message; }); setFieldErrors(mapped); } else { setError(requestError instanceof ApiClientError ? requestError.message : "Unable to save employee."); } } finally { setSubmitting(false); } } if (loading) return <LoadingSkeleton rows={6} />; return <div className="space-y-6"><Link to={id ? `/employees/${id}` : "/employees"} className="text-sm font-semibold text-indigo-600">← Cancel and go back</Link><div><p className="text-sm font-semibold text-indigo-600">PEOPLE OPERATIONS</p><h1 className="mt-2 text-3xl font-bold tracking-tight">{id ? "Edit employee" : "Create employee"}</h1><p className="mt-2 text-sm text-slate-600">Use the fields and values supported by the employee API.</p></div>{error && <div className="rounded-xl border border-rose-200 bg-rose-50 p-4 text-sm text-rose-800" role="alert">{error}</div>}<EmployeeForm employee={employee} departments={departments} onSubmit={save} onCancel={() => navigate(id ? `/employees/${id}` : "/employees")} isSubmitting={submitting} /></div>; }

