import { useEffect, useState } from "react";
import { Link, useLocation, useParams } from "react-router-dom";
import { LoadingSkeleton } from "../components/ui/LoadingSkeleton";
import { useAuth } from "../features/auth/AuthContext";
import { employeeLabel, formatDate, sentimentLabel } from "../features/engagement/engagementUtils";
import { ApiClientError } from "../services/apiClient";
import { getEmployee } from "../services/employeeApi";
import { getFeedback } from "../services/feedbackApi";

export function FeedbackDetailsPage() {
  const { id } = useParams(); const location = useLocation(); const { user } = useAuth(); const [feedback, setFeedback] = useState(location.state?.feedback ?? null); const [employee, setEmployee] = useState(location.state?.employee ?? null); const [error, setError] = useState(""); const returnPath = user.role === "employee" ? "/dashboard" : "/feedback";
  useEffect(() => { getFeedback(id).then((result) => { setFeedback(result.feedback); const employeeId = result.feedback.employee?._id ?? result.feedback.employee; return !employee && employeeId ? getEmployee(employeeId).then((employeeResult) => setEmployee(employeeResult.employee)).catch(() => undefined) : undefined; }).catch((requestError) => setError(requestError instanceof ApiClientError ? requestError.message : "Unable to load this feedback.")); }, [id]);
  return <div className="space-y-6"><Link to={returnPath} className="text-sm font-semibold text-indigo-600">← Back</Link>{error ? <div className="rounded-2xl border border-rose-200 bg-rose-50 p-6 text-sm text-rose-800">{error}</div> : feedback ? <><div><p className="text-sm font-semibold text-indigo-600">FEEDBACK DETAIL</p><h1 className="mt-2 text-3xl font-bold tracking-tight">Employee feedback</h1><p className="mt-2 text-sm text-slate-600">{employeeLabel(employee ?? feedback.employee)} · {formatDate(feedback.submittedAt)}</p></div><section className="grid gap-5 sm:grid-cols-2"><article className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><p className="text-xs font-semibold uppercase tracking-wide text-slate-400">Sentiment</p><p className="mt-2 text-2xl font-bold text-slate-900">{sentimentLabel(feedback.sentimentLabel)}</p><p className="mt-2 text-sm text-slate-500">Score: {feedback.sentimentScore ?? "Not available"}</p></article><article className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><p className="text-xs font-semibold uppercase tracking-wide text-slate-400">Submitted</p><p className="mt-2 text-2xl font-bold text-slate-900">{formatDate(feedback.submittedAt)}</p></article></section><article className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><p className="text-xs font-semibold uppercase tracking-wide text-slate-400">Feedback</p><p className="mt-3 whitespace-pre-wrap text-sm leading-7 text-slate-700">{feedback.text}</p></article></> : <LoadingSkeleton rows={6} />}</div>;
}
