import { useEffect, useState } from "react";
import { formatDate } from "../features/engagement/engagementUtils";
import { listEmployees } from "../services/employeeApi";
import { generateManagerCoaching } from "../services/managerCoachApi";
import { ApiClientError } from "../services/apiClient";

const sectionLabels = { employeeSummary: "Employee summary", riskAssessment: "Risk assessment", topAttritionDrivers: "Top attrition drivers", performanceObservations: "Performance observations", attendanceObservations: "Attendance observations", feedbackTrends: "Feedback trends", surveyTrends: "Survey trends", relevantHrPolicies: "Relevant HR policies", immediateRecommendations: "Immediate recommendations (30 days)", mediumTermRecommendations: "Medium-term recommendations (90 days)", suggestedManagerConversation: "Suggested manager conversation", confidenceStatement: "Confidence statement" };

export function ManagerCoachPage() {
  const [employees, setEmployees] = useState([]); const [employeeId, setEmployeeId] = useState(""); const [report, setReport] = useState(null); const [loadingEmployees, setLoadingEmployees] = useState(true); const [generating, setGenerating] = useState(false); const [error, setError] = useState("");
  useEffect(() => { listEmployees().then((result) => { const items = result.employees ?? []; setEmployees(items); if (items.length) setEmployeeId(items[0]._id); }).catch((requestError) => setError(requestError instanceof ApiClientError ? requestError.message : "Unable to load available employees.")).finally(() => setLoadingEmployees(false)); }, []);
  async function generate() { if (!employeeId) return; setGenerating(true); setError(""); try { setReport(await generateManagerCoaching(employeeId)); } catch (requestError) { setError(requestError instanceof ApiClientError ? requestError.message : "Unable to generate a coaching report."); } finally { setGenerating(false); } }
  return <div className="space-y-6 print:space-y-4"><section className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end print:hidden"><div><p className="text-sm font-semibold text-indigo-600">MANAGER ENABLEMENT</p><h1 className="mt-2 text-3xl font-bold tracking-tight sm:text-4xl">Manager Coaching Agent</h1><p className="mt-3 max-w-3xl text-sm leading-6 text-slate-600">Generate a structured, evidence-backed coaching brief from authorized employee signals and relevant HR policy sources.</p></div>{report && <button onClick={() => window.print()} className="rounded-lg border border-slate-300 bg-white px-4 py-2.5 text-sm font-semibold text-slate-700 hover:bg-slate-50">Print / export</button>}</section><section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm print:hidden"><div className="grid gap-4 md:grid-cols-[1fr_auto]"><label className="text-sm font-semibold text-slate-700">Employee<select value={employeeId} disabled={loadingEmployees || generating} onChange={(event) => { setEmployeeId(event.target.value); setReport(null); }} className="mt-2 block w-full rounded-lg border border-slate-300 bg-white px-3 py-2.5 text-sm font-normal"><option value="">Select an employee</option>{employees.map((employee) => <option key={employee._id} value={employee._id}>{employee.employeeCode} · {employee.designation}</option>)}</select></label><button disabled={!employeeId || generating || loadingEmployees} onClick={generate} className="self-end rounded-lg bg-indigo-600 px-5 py-2.5 text-sm font-semibold text-white hover:bg-indigo-700 disabled:cursor-not-allowed disabled:opacity-50">{generating ? "Building report…" : "Generate report"}</button></div><p className="mt-3 text-xs leading-5 text-slate-500">The agent uses only backend-collected evidence and approved policy excerpts. Missing data is identified rather than assumed.</p></section>{error && <div className="rounded-2xl border border-rose-200 bg-rose-50 p-5 text-sm text-rose-800" role="alert">{error}</div>}{generating && <LoadingReport />}{report && <CoachingReport result={report} />}</div>;
}

function CoachingReport({ result }) { const { report, evidence, policySources, confidence, generatedAt } = result; const prediction = evidence.attrition; return <div className="space-y-5"><section className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><div className="flex flex-col justify-between gap-4 sm:flex-row"><div><p className="text-xs font-semibold uppercase tracking-wide text-slate-400">Evidence-backed coaching brief</p><h2 className="mt-2 text-2xl font-bold">{evidence.employee.employeeCode} · {evidence.employee.designation}</h2><p className="mt-2 text-sm text-slate-600">{evidence.employee.department} · Generated {formatDate(generatedAt)}</p></div><span className={`h-fit rounded-full px-3 py-1.5 text-xs font-semibold ${confidence.level === "high" ? "bg-emerald-50 text-emerald-700" : confidence.level === "medium" ? "bg-amber-50 text-amber-700" : "bg-slate-100 text-slate-700"}`}>{confidence.level} evidence coverage · {Math.round(confidence.score * 100)}%</span></div>{confidence.missingInformation?.length ? <p className="mt-5 rounded-xl border border-amber-200 bg-amber-50 p-3 text-sm text-amber-800">Unavailable evidence: {confidence.missingInformation.join(", ")}.</p> : null}</section><section className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><Metric label="Attrition probability" value={prediction ? `${(prediction.probability * 100).toFixed(1)}%` : "Unavailable"} /><Metric label="Risk level" value={prediction?.riskLevel ?? "Unavailable"} /><Metric label="Absence rate" value={evidence.attendance?.absenceRate != null ? `${(evidence.attendance.absenceRate * 100).toFixed(1)}%` : "Unavailable"} /><Metric label="Performance average" value={evidence.performance?.averageRating != null ? `${evidence.performance.averageRating}/5` : "Unavailable"} /></section><section className="grid gap-5 lg:grid-cols-[1.4fr_0.6fr]"><div className="space-y-3">{Object.entries(sectionLabels).map(([key, title], index) => <ReportSection key={key} title={title} value={report[key]} open={index < 2} />)}</div><EvidenceAside prediction={prediction} policySources={policySources} evidence={evidence} /></section></div>; }
function Metric({ label, value }) { return <article className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><p className="text-xs font-semibold uppercase tracking-wide text-slate-400">{label}</p><p className="mt-2 text-xl font-bold text-slate-900">{value}</p></article>; }
function ReportSection({ title, value, open }) { const items = Array.isArray(value) ? value : null; return <details open={open} className="rounded-2xl border border-slate-200 bg-white shadow-sm"><summary className="cursor-pointer list-none px-5 py-4 text-sm font-bold text-slate-900">{title}</summary><div className="border-t border-slate-100 px-5 py-4 text-sm leading-7 text-slate-700">{items ? items.length ? <ul className="space-y-2">{items.map((item, index) => <li key={index} className="flex gap-2"><span className="text-indigo-500">•</span><span>{item}</span></li>)}</ul> : <p>Unavailable or not supported by the supplied evidence.</p> : <p className="whitespace-pre-wrap">{value || "Unavailable or not supported by the supplied evidence."}</p>}</div></details>; }
function EvidenceAside({ prediction, policySources, evidence }) { return <aside className="space-y-4"><section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h3 className="font-bold text-slate-900">SHAP factors</h3>{prediction?.shapFactors?.length ? <div className="mt-4 space-y-3">{prediction.shapFactors.map((factor) => <div key={`${factor.rank}-${factor.feature}`}><div className="flex items-center justify-between gap-2 text-sm"><span className="font-medium">{factor.rank}. {factor.feature}</span><span className={factor.direction === "increase risk" ? "text-rose-600" : "text-emerald-600"}>{factor.direction === "increase risk" ? "Risk" : "Protective"}</span></div><div className="mt-1 h-1.5 rounded-full bg-slate-100"><div className={factor.direction === "increase risk" ? "h-full rounded-full bg-rose-400" : "h-full rounded-full bg-emerald-400"} style={{ width: `${Math.min(100, Math.max(8, factor.importance * 100))}%` }} /></div></div>)}</div> : <p className="mt-3 text-sm text-slate-500">No SHAP explanation is available.</p>}</section><section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h3 className="font-bold text-slate-900">Referenced HR policies</h3>{policySources?.length ? <div className="mt-4 space-y-2">{policySources.map((source) => <details key={source.id} className="rounded-lg border border-slate-100 p-3"><summary className="cursor-pointer list-none text-sm font-semibold"><span className="mr-2 text-indigo-600">[{source.id}]</span>{source.document}</summary><p className="mt-1 text-xs text-slate-500">{source.section} · {(source.score * 100).toFixed(0)}% match</p><p className="mt-3 border-t border-slate-100 pt-3 text-sm leading-6 text-slate-600">{source.excerpt}</p></details>)}</div> : <p className="mt-3 text-sm text-slate-500">No sufficiently relevant HR policy sources were retrieved.</p>}</section><section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h3 className="font-bold text-slate-900">Supporting metrics</h3><dl className="mt-3 space-y-2 text-sm"><MetricRow label="Attendance periods" value={evidence.attendance?.periodsReviewed ?? "Unavailable"} /><MetricRow label="Survey responses" value={evidence.surveys?.responsesReviewed ?? "Unavailable"} /><MetricRow label="Feedback responses" value={evidence.feedback?.responsesReviewed ?? "Unavailable"} /><MetricRow label="Prediction model" value={prediction?.modelVersion ?? "Unavailable"} /></dl></section></aside>; }
function MetricRow({ label, value }) { return <div className="flex justify-between gap-4"><dt className="text-slate-500">{label}</dt><dd className="text-right font-semibold text-slate-800">{value}</dd></div>; }
function LoadingReport() { return <div className="space-y-4" aria-live="polite"><div className="rounded-2xl border border-indigo-100 bg-indigo-50 p-5 text-sm text-indigo-800">Collecting authorized employee evidence, retrieving policy sources, and drafting a grounded coaching brief…</div>{Array.from({ length: 4 }, (_, index) => <div key={index} className="h-24 animate-pulse rounded-2xl bg-slate-100" />)}</div>; }
