import { useEffect, useState } from "react";
import { Link, useLocation, useNavigate, useParams } from "react-router-dom";
import { LoadingSkeleton } from "../components/ui/LoadingSkeleton";
import { useAuth } from "../features/auth/AuthContext";
import { employeeLabel, formatReviewPeriod, ratingLabel, reviewerLabel } from "../features/performance-reviews/reviewUtils";
import { ApiClientError } from "../services/apiClient";
import { getEmployee } from "../services/employeeApi";
import { getPerformanceReview } from "../services/performanceReviewApi";

export function PerformanceReviewDetailsPage() {
  const { id } = useParams(); const location = useLocation(); const navigate = useNavigate(); const { user } = useAuth(); const [review, setReview] = useState(location.state?.review ?? null); const [employee, setEmployee] = useState(location.state?.employee ?? null); const [error, setError] = useState("");
  useEffect(() => { getPerformanceReview(id).then((result) => { const nextReview = result.review; setReview(nextReview); const employeeId = nextReview.employee?._id ?? nextReview.employee; return !employee && employeeId ? getEmployee(employeeId).then((employeeResult) => setEmployee(employeeResult.employee)).catch(() => undefined) : undefined; }).catch((requestError) => setError(requestError instanceof ApiClientError ? requestError.message : "Unable to load this performance review.")); }, [id]);
  const reviewerId = review?.reviewer?._id ?? review?.reviewer?.id ?? review?.reviewer; const canEdit = Boolean(review && (["hr", "admin"].includes(user.role) || (user.role === "manager" && reviewerId === user.id)));
  return <div className="space-y-6"><div className="flex items-center justify-between gap-3"><Link to="/performance-reviews" className="text-sm font-semibold text-indigo-600">← Back to reviews</Link>{canEdit && <button onClick={() => navigate(`/performance-reviews/${id}/edit`, { state: { review, employee } })} className="rounded-lg border border-slate-300 px-4 py-2 text-sm font-semibold">Edit review</button>}</div>{error ? <div className="rounded-2xl border border-rose-200 bg-rose-50 p-6 text-sm text-rose-800" role="alert">{error}</div> : review ? <><div><p className="text-sm font-semibold text-indigo-600">PERFORMANCE REVIEW</p><h1 className="mt-2 text-3xl font-bold tracking-tight">{formatReviewPeriod(review.reviewPeriod)}</h1></div><section className="grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{[["Employee", employeeLabel(employee ?? review.employee)], ["Reviewer", reviewerLabel(review.reviewer)], ["Rating", ratingLabel(review.rating)], ["Review period", formatReviewPeriod(review.reviewPeriod)], ["Review date", review.createdAt ? new Intl.DateTimeFormat(undefined, { dateStyle: "medium" }).format(new Date(review.createdAt)) : "Not available"]].map(([label, value]) => <article key={label} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><p className="text-xs font-semibold uppercase tracking-wide text-slate-400">{label}</p><p className="mt-2 text-lg font-semibold text-slate-900">{value}</p></article>)}</section><section className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><p className="text-xs font-semibold uppercase tracking-wide text-slate-400">Comments and goals</p><p className="mt-3 whitespace-pre-wrap text-sm leading-7 text-slate-700">{review.comments || "No comments or goals were included in this review."}</p><p className="mt-5 text-xs text-slate-500">Goals are not a separate field in the current backend contract.</p></section></> : <LoadingSkeleton rows={6} />}</div>;
}
