import { useEffect, useState } from "react";
import { Link, useLocation, useNavigate, useParams } from "react-router-dom";
import { PerformanceReviewForm } from "../components/performance-reviews/PerformanceReviewForm";
import { LoadingSkeleton } from "../components/ui/LoadingSkeleton";
import { listEmployees } from "../services/employeeApi";
import { createPerformanceReview, getPerformanceReview, updatePerformanceReview } from "../services/performanceReviewApi";
import { ApiClientError } from "../services/apiClient";
import { useToast } from "../features/toasts/ToastContext";

export function PerformanceReviewFormPage() { const { id } = useParams(); const location = useLocation(); const navigate = useNavigate(); const { showToast } = useToast(); const [review, setReview] = useState(location.state?.review ?? null); const [employees, setEmployees] = useState([]); const [loading, setLoading] = useState(Boolean(id && !review)); const [error, setError] = useState(""); const [submitting, setSubmitting] = useState(false); useEffect(() => { Promise.all([listEmployees(), id && !review ? getPerformanceReview(id) : Promise.resolve({ review: null })]).then(([employeeResult, reviewResult]) => { setEmployees(employeeResult.employees ?? []); if (!review && id) setReview(reviewResult.review); }).catch((requestError) => setError(requestError instanceof ApiClientError ? requestError.message : "Unable to prepare the review form.")).finally(() => setLoading(false)); }, [id]); async function save(payload, setFieldErrors) { setSubmitting(true); try { const result = id ? await updatePerformanceReview(id, payload) : await createPerformanceReview(payload); showToast(id ? "Performance review updated." : "Performance review created."); navigate(`/performance-reviews/${result.review._id}`); } catch (requestError) { if (requestError.details?.length) { const mapped = {}; requestError.details.forEach((detail) => { mapped[detail.field || "form"] = detail.message; }); setFieldErrors(mapped); } else setError(requestError instanceof ApiClientError ? requestError.message : "Unable to save performance review."); } finally { setSubmitting(false); } } if (loading) return <LoadingSkeleton rows={6} />; return <div className="space-y-6"><Link to={id ? `/performance-reviews/${id}` : "/performance-reviews"} className="text-sm font-semibold text-indigo-600">← Cancel and go back</Link><div><p className="text-sm font-semibold text-indigo-600">PEOPLE DEVELOPMENT</p><h1 className="mt-2 text-3xl font-bold tracking-tight">{id ? "Edit performance review" : "Create performance review"}</h1><p className="mt-2 text-sm text-slate-600">Use the fields supported by the performance review API.</p></div>{error && <div className="rounded-xl border border-rose-200 bg-rose-50 p-4 text-sm text-rose-800" role="alert">{error}</div>}<PerformanceReviewForm review={review} employees={employees} onSubmit={save} onCancel={() => navigate(id ? `/performance-reviews/${id}` : "/performance-reviews")} isSubmitting={submitting} /></div>; }

