import { useEffect, useMemo, useState } from "react";
import { useNavigate } from "react-router-dom";
import { DataTable } from "../components/ui/DataTable";
import { LoadingSkeleton } from "../components/ui/LoadingSkeleton";
import { Pagination } from "../components/ui/Pagination";
import { SearchBar } from "../components/ui/SearchBar";
import { listPerformanceReviews } from "../services/performanceReviewApi";
import { listEmployees } from "../services/employeeApi";
import { ApiClientError } from "../services/apiClient";
import { employeeLabel, formatReviewPeriod, ratingLabel, reviewerLabel } from "../features/performance-reviews/reviewUtils";

export function PerformanceReviewsPage() { const navigate = useNavigate(); const [reviews, setReviews] = useState([]); const [employees, setEmployees] = useState([]); const [query, setQuery] = useState(""); const [filters, setFilters] = useState({ employee: "", reviewer: "", rating: "", reviewPeriod: "" }); const [sort, setSort] = useState("createdAt"); const [page, setPage] = useState(1); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const pageSize = 8;
  function load() { setLoading(true); Promise.all([listPerformanceReviews({ employee: filters.employee, reviewer: filters.reviewer, reviewPeriod: filters.reviewPeriod }), listEmployees().catch(() => ({ employees: [] }))]).then(([reviewResult, employeeResult]) => { setReviews(reviewResult.reviews ?? []); setEmployees(employeeResult.employees ?? []); setError(""); }).catch((requestError) => setError(requestError instanceof ApiClientError ? requestError.message : "Unable to load performance reviews.")).finally(() => setLoading(false)); }
  useEffect(() => { load(); }, [filters.employee, filters.reviewer, filters.reviewPeriod]);
  const employeeMap = useMemo(() => new Map(employees.map((employee) => [employee._id, employee])), [employees]);
  const visible = useMemo(() => { const needle = query.toLowerCase().trim(); return reviews.filter((review) => { const employee = employeeMap.get(review.employee?._id ?? review.employee); const text = `${employeeLabel(employee)} ${reviewerLabel(review.reviewer)} ${review.reviewPeriod} ${review.comments ?? ""}`.toLowerCase(); return (!needle || text.includes(needle)) && (!filters.rating || String(review.rating) === filters.rating); }).sort((a, b) => sort === "rating" ? b.rating - a.rating : sort === "period" ? String(b.reviewPeriod).localeCompare(String(a.reviewPeriod)) : new Date(b.createdAt ?? 0) - new Date(a.createdAt ?? 0)); }, [employeeMap, filters.rating, query, reviews, sort]);
  const pageCount = Math.max(1, Math.ceil(visible.length / pageSize)); const rows = visible.slice((page - 1) * pageSize, page * pageSize); function filter(key, value) { setFilters((current) => ({ ...current, [key]: value })); setPage(1); }
  const columns = [{ key: "employee", header: "Employee", render: (row) => <span className="font-semibold text-slate-900">{employeeLabel(employeeMap.get(row.employee?._id ?? row.employee))}</span> }, { key: "reviewer", header: "Reviewer", render: (row) => reviewerLabel(row.reviewer) }, { key: "reviewPeriod", header: "Review period", render: (row) => formatReviewPeriod(row.reviewPeriod) }, { key: "rating", header: "Rating", render: (row) => <span className="rounded-full bg-indigo-50 px-2.5 py-1 text-xs font-semibold text-indigo-700">{ratingLabel(row.rating)}</span> }, { key: "createdAt", header: "Recorded", render: (row) => row.createdAt ? new Intl.DateTimeFormat(undefined, { dateStyle: "medium" }).format(new Date(row.createdAt)) : "Not available" }];
  return <div className="space-y-6"><section className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="text-sm font-semibold text-indigo-600">PEOPLE DEVELOPMENT</p><h1 className="mt-2 text-3xl font-bold tracking-tight">Performance reviews</h1><p className="mt-2 text-sm text-slate-600">Review performance conversations and ratings within your authorized scope.</p></div><button onClick={() => navigate("/performance-reviews/new")} className="rounded-lg bg-indigo-600 px-4 py-2.5 text-sm font-semibold text-white hover:bg-indigo-700">Create review</button></section><div className="grid gap-3 rounded-2xl border border-slate-200 bg-white p-4 lg:grid-cols-[1fr_auto_auto_auto_auto] lg:items-center"><SearchBar value={query} onChange={(value) => { setQuery(value); setPage(1); }} /><select aria-label="Employee filter" value={filters.employee} onChange={(event) => filter("employee", event.target.value)} className="rounded-lg border border-slate-300 bg-white px-3 py-2.5 text-sm"><option value="">All employees</option>{employees.map((employee) => <option key={employee._id} value={employee._id}>{employee.employeeCode}</option>)}</select><input aria-label="Reviewer filter" value={filters.reviewer} onChange={(event) => filter("reviewer", event.target.value)} placeholder="Reviewer ID" className="rounded-lg border border-slate-300 px-3 py-2.5 text-sm" /><input aria-label="Review date filter" value={filters.reviewPeriod} onChange={(event) => filter("reviewPeriod", event.target.value)} placeholder="Review period" className="rounded-lg border border-slate-300 px-3 py-2.5 text-sm" /><select aria-label="Rating filter" value={filters.rating} onChange={(event) => filter("rating", event.target.value)} className="rounded-lg border border-slate-300 bg-white px-3 py-2.5 text-sm"><option value="">All ratings</option>{[1, 2, 3, 4, 5].map((rating) => <option key={rating} value={rating}>{rating}/5</option>)}</select><select aria-label="Sort reviews" value={sort} onChange={(event) => setSort(event.target.value)} className="rounded-lg border border-slate-300 bg-white px-3 py-2.5 text-sm"><option value="createdAt">Most recent</option><option value="period">Review period</option><option value="rating">Highest rating</option></select></div>{loading ? <LoadingSkeleton /> : error ? <div className="rounded-2xl border border-rose-200 bg-rose-50 p-6 text-sm text-rose-800" role="alert">{error}<button onClick={load} className="ml-3 font-semibold underline">Retry</button></div> : <><DataTable columns={columns} rows={rows} onRowClick={(row) => navigate(`/performance-reviews/${row._id}`, { state: { review: row, employee: employeeMap.get(row.employee?._id ?? row.employee) } })} emptyMessage="No performance reviews match your search and filters." /><Pagination page={page} pageCount={pageCount} total={visible.length} onChange={setPage} /></>}</div>; }

