import { useEffect, useState } from "react";
import { Link, useLocation, useParams } from "react-router-dom";
import { LoadingSkeleton } from "../components/ui/LoadingSkeleton";
import { getEmployee } from "../services/employeeApi";
import { getSurvey } from "../services/surveyApi";
import { ApiClientError } from "../services/apiClient";
import { employeeLabel, formatDate, surveyFields, surveyLabels } from "../features/engagement/engagementUtils";

export function SurveyDetailsPage() { const { id } = useParams(); const location = useLocation(); const [survey, setSurvey] = useState(location.state?.survey ?? null); const [employee, setEmployee] = useState(location.state?.employee ?? null); const [error, setError] = useState(""); useEffect(() => { getSurvey(id).then((result) => { setSurvey(result.survey); const employeeId = result.survey.employee?._id ?? result.survey.employee; if (!employee && employeeId) return getEmployee(employeeId).then((employeeResult) => setEmployee(employeeResult.employee)).catch(() => undefined); return undefined; }).catch((requestError) => setError(requestError instanceof ApiClientError ? requestError.message : "Unable to load this survey.")); }, [id]); return <div className="space-y-6"><Link to="/surveys" className="text-sm font-semibold text-indigo-600">← Back to surveys</Link>{error ? <div className="rounded-2xl border border-rose-200 bg-rose-50 p-6 text-sm text-rose-800">{error}</div> : survey ? <><div><p className="text-sm font-semibold text-indigo-600">SURVEY RESPONSE</p><h1 className="mt-2 text-3xl font-bold tracking-tight">Employee satisfaction response</h1><p className="mt-2 text-sm text-slate-600">{employeeLabel(employee ?? survey.employee)} · {formatDate(survey.submittedAt)}</p></div><section className="grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{surveyFields.map((field) => <article key={field} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><p className="text-xs font-semibold uppercase tracking-wide text-slate-400">{surveyLabels[field]}</p><p className="mt-2 text-2xl font-bold text-slate-900">{survey[field]}/5</p></article>)}</section><p className="text-sm text-slate-500">Survey results are available as individual responses; no aggregate results endpoint exists.</p></> : <LoadingSkeleton rows={6} />}</div>; }

