import { useEffect, useState } from "react";
import { idOf, statuses } from "../../features/employees/employeeUtils";

const blank = { user: "", employeeCode: "", department: "", manager: "", designation: "", dateOfJoining: "", age: "", salary: "", employmentStatus: "active", lastPromotionDate: "" };
function initialValues(employee) { return employee ? { ...blank, ...employee, user: idOf(employee.user) ?? "", department: idOf(employee.department) ?? "", manager: idOf(employee.manager) ?? "", dateOfJoining: employee.dateOfJoining?.slice(0, 10) ?? "", lastPromotionDate: employee.lastPromotionDate?.slice(0, 10) ?? "" } : blank; }

export function EmployeeForm({ employee, departments, onSubmit, onCancel, isSubmitting }) {
  const [values, setValues] = useState(initialValues(employee));
  const [errors, setErrors] = useState({});
  useEffect(() => setValues(initialValues(employee)), [employee]);
  function change(event) { setValues((current) => ({ ...current, [event.target.name]: event.target.value })); setErrors((current) => ({ ...current, [event.target.name]: "" })); }
  function validate() { const next = {}; ["employeeCode", "department", "designation", "dateOfJoining", "age", "salary", "employmentStatus"].forEach((field) => { if (!values[field]) next[field] = "This field is required."; }); if (!employee && !values.user) next.user = "User reference is required."; if (values.age && (Number(values.age) < 16 || Number(values.age) > 100)) next.age = "Age must be between 16 and 100."; if (values.employeeCode && (values.employeeCode.trim().length < 3 || values.employeeCode.trim().length > 30)) next.employeeCode = "Use 3–30 characters."; setErrors(next); return !Object.keys(next).length; }
  async function submit(event) { event.preventDefault(); if (!validate()) return; const payload = { ...values, manager: values.manager || null, lastPromotionDate: values.lastPromotionDate || null, age: Number(values.age), salary: Number(values.salary) }; if (employee) delete payload.user; await onSubmit(payload, setErrors); }
  const field = (name, label, type = "text", extra = {}) => <label className="block text-sm font-semibold text-slate-700">{label}<input name={name} type={type} value={values[name] ?? ""} onChange={change} className={`mt-2 w-full rounded-lg border px-3 py-2.5 font-normal outline-none focus:border-indigo-500 ${errors[name] ? "border-rose-400" : "border-slate-300"}`} {...extra} />{errors[name] && <span className="mt-1 block text-xs font-normal text-rose-700">{errors[name]}</span>}</label>;
  return <form onSubmit={submit} className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm sm:p-8"><div className="grid gap-5 sm:grid-cols-2">{!employee && <>{field("user", "User ID", "text", { placeholder: "Existing User ObjectId" })}<div className="rounded-lg bg-amber-50 p-3 text-xs font-normal leading-5 text-amber-900 sm:col-span-1">Employee creation requires an existing user ID because the backend exposes no user-management endpoint here.</div></>}{field("employeeCode", "Employee code", "text", { maxLength: 30 })}<label className="block text-sm font-semibold text-slate-700">Department<select name="department" value={values.department} onChange={change} className={`mt-2 w-full rounded-lg border bg-white px-3 py-2.5 font-normal outline-none focus:border-indigo-500 ${errors.department ? "border-rose-400" : "border-slate-300"}`}><option value="">Select department</option>{departments.map((item) => <option key={item._id} value={item._id}>{item.name}</option>)}</select>{errors.department && <span className="mt-1 block text-xs font-normal text-rose-700">{errors.department}</span>}</label>{field("designation", "Designation", "text", { maxLength: 100 })}{field("dateOfJoining", "Date of joining", "date")}{field("age", "Age", "number", { min: 16, max: 100 })}{field("salary", "Salary", "number", { min: 0, step: "0.01" })}<label className="block text-sm font-semibold text-slate-700">Employment status<select name="employmentStatus" value={values.employmentStatus} onChange={change} className="mt-2 w-full rounded-lg border border-slate-300 bg-white px-3 py-2.5 font-normal outline-none focus:border-indigo-500">{statuses.map((status) => <option key={status} value={status}>{status.replace("_", " ")}</option>)}</select></label>{field("manager", "Manager ID (optional)", "text", { placeholder: "Employee ObjectId" })}{field("lastPromotionDate", "Last promotion date (optional)", "date")}</div><div className="mt-7 flex justify-end gap-3"><button type="button" onClick={onCancel} className="rounded-lg border border-slate-300 px-4 py-2.5 text-sm font-semibold">Cancel</button><button disabled={isSubmitting} className="rounded-lg bg-indigo-600 px-5 py-2.5 text-sm font-semibold text-white hover:bg-indigo-700 disabled:opacity-50">{isSubmitting ? "Saving…" : employee ? "Save changes" : "Create employee"}</button></div></form>;
}

